In [1]:
# ctrl v to paste the path
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L17"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L17

In [2]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L17'

In [3]:
%ls

L17.ipynb  __pycache__/   top10rows_NoIndex.csv
m1.py      top10rows.csv  us-cities-top-1k.csv

In [4]:
import pandas as pd

In [5]:
df1=pd.read_csv("us-cities-top-1k.csv")
#print(df1)
df1 # print(df1)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [6]:
# head() tail()
df=df1.head(10)
print(df)

         City           State  Population        lat         lon
0  Marysville      Washington       63269  48.051764 -122.177082
1      Perris      California       72326  33.782519 -117.228648
2   Cleveland            Ohio      390113  41.499320  -81.694361
3   Worcester   Massachusetts      182544  42.262593  -71.802293
4    Columbia  South Carolina      133358  34.000710  -81.034814
5   Waterbury     Connecticut      109676  41.558153  -73.051496
6       Eagan       Minnesota       65453  44.804132  -93.166886
7  Southfield        Michigan       73006  42.473369  -83.221873
8   Lafayette       Louisiana      124276  30.224090  -92.019843
9  Boise City           Idaho      214237  43.618710 -116.214607

In [7]:
df.to_csv("top10rows.csv",index=True) # save to file
df.to_csv("top10rows_NoIndex.csv",index=False)

In [8]:
%ls

L17.ipynb  __pycache__/   top10rows_NoIndex.csv
m1.py      top10rows.csv  us-cities-top-1k.csv

In [9]:
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L17"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L17

In [10]:
import random
n=random.randint(1,10)
print(n)

3

In [11]:
# random: folder, file
# library, module, package #
# L17 ipynb:interactive python notebook
#.py

In [12]:
%ls

L17.ipynb  __pycache__/   top10rows_NoIndex.csv
m1.py      top10rows.csv  us-cities-top-1k.csv

In [13]:
# m1.py is a file
#
print(pi)
print(num1)

NameError: name 'pi' is not defined

In [14]:
import m1
print(m1.pi)
print(m1.num1)

3.14
20

In [15]:
import m1 as m
print(m.pi)
print(m.num1)

3.14
20

In [20]:
%ls

L17.ipynb  __pycache__/   top10rows_NoIndex.csv
m1.py      top10rows.csv  us-cities-top-1k.csv

In [16]:
# commands
# not python code
# print working directory (currrent foler)
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L17'

In [17]:
# list all files and folders
%ls

L17.ipynb  __pycache__/   top10rows_NoIndex.csv
m1.py      top10rows.csv  us-cities-top-1k.csv

In [18]:
# change directory (folder)
# %cd ""

In [19]:
# us-cities-top-1k.csv
# python basics
# Python (Java, Corola Sedan, => UHaul  )
# Packages (Pandas) -- numpy, matplotlib
# files (Database is file)
# csv: comma seperate values
# CPU RAM
# file: hard drive
import pandas
pandas.read_csv("us-cities-top-1k.csv")

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [21]:
import pandas as pd
pd.read_csv("us-cities-top-1k.csv")
# read_csv(): load data file from hard drive into RAM

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]