In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L23Pandas"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L23Pandas

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L23Pandas'

In [ ]:
%ls

L23_LCP.ipynb  tips.csv

In [ ]:
import pandas as pd

In [ ]:
mdf=pd.read_csv("tips.csv")
mdf

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
# get all column names
mdf.columns

Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
# get a single column: it is series
s=mdf["tip"]
s

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [ ]:
# add a new column based on the old column
s=mdf["tip"]+1.0
mdf["NEW_TIPS"]=mdf["tip"]+1.0
mdf["NEW_TIPS2"]=s
mdf

,ID,total_bill,tip,sex,smoker,day,time,size,NEW_TIPS,NEW_TIPS2
0,1,16.99,1.01,Female,No,Sun,Dinner,2,2.01,2.01
1,2,10.34,1.66,Male,No,Sun,Dinner,3,2.66,2.66
2,3,21.01,3.50,Male,No,Sun,Dinner,3,4.50,4.50
3,4,23.68,3.31,Male,No,Sun,Dinner,2,4.31,4.31
4,5,24.59,3.61,Female,No,Sun,Dinner,4,4.61,4.61
...,...,...,...,...,...,...,...,...,...,...
239,240,29.03,5.92,Male,No,Sat,Dinner,3,6.92,6.92
240,241,27.18,2.00,Female,Yes,Sat,Dinner,2,3.00,3.00
241,242,22.67,2.00,Male,Yes,Sat,Dinner,2,3.00,3.00
242,243,17.82,1.75,Male,No,Sat,Dinner,2,2.75,2.75
243,244,18.78,3.00,Female,No,Thur,Dinner,2,4.00,4.00

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L23Pandas'

In [ ]:
%ls

L23.ipynb  tips.csv

In [ ]:
import pandas as pd

In [ ]:
mdf=pd.read_csv("tips.csv") #
mdf

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
# pandas: file,folder,module,package,library
# import as
# dataframe, table
# series
# collections:
l=[2,3,9]# walls or boundary of a warehouse
# len()
n=len(l)
print(n)
#
s=mdf["day"]#.
print(s)
# len() mdf s
#
n=len(s)
print(n)
#
n=len(mdf)# rows
print(n)
#
# funs for df: head(x) tail(3) sort_values() groupby()
#funs for s: max() min() mean() count() value_counts() unique()

3
0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: object
244
244

In [ ]:
s=mdf["day"]
print(s)
c=s.unique() #
print(c)
n=len(c)
print(n)
s.value_counts()

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: object
['Sun' 'Sat' 'Thur' 'Fri']
4

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
mdf.columns

Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
s=mdf["time"]
print(s)
c=s.unique() #
print(c)
n=len(c)
print(n)
s.value_counts()

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: object
['Dinner' 'Lunch']
2

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
s=mdf["size"]
print(s)
c=s.unique() #
print(c)
n=len(c)
print(n)
s.value_counts()

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64
[2 3 4 1 6 5]
6

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [ ]:
s=mdf["tip"]
print(s) # max() min() mean() sum()
n=s.sum()
print(f"Sum of tips: ${n:.2f}")
n=s.max()
print(n)
n=s.min()
print(n)
n=s.mean()
print(n)

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
Sum of tips: $731.58
10.0
1.0
2.99827868852459

In [ ]:
mdf.columns

Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
s=mdf['total_bill']
print(s) # max() min() mean() sum()
n=s.sum()
print(f"Sum of bills: ${n:.2f}")
n=s.max()
print(n)
n=s.min()
print(n)
n=s.mean()
print(n)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64
Sum of bills: $4827.77
50.81
3.07
19.78594262295082

In [ ]:
mdf.columns

Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
mdf

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
s1=mdf['total_bill']
s2=mdf['tip']
mdf["NC1"]=s2+2.5
mdf["NC2"]=s1*1.2
mdf["total"]=s1+s2
mdf

,ID,total_bill,tip,sex,smoker,day,time,size,NC1,NC2,total
0,1,16.99,1.01,Female,No,Sun,Dinner,2,3.51,20.388,18.00
1,2,10.34,1.66,Male,No,Sun,Dinner,3,4.16,12.408,12.00
2,3,21.01,3.50,Male,No,Sun,Dinner,3,6.00,25.212,24.51
3,4,23.68,3.31,Male,No,Sun,Dinner,2,5.81,28.416,26.99
4,5,24.59,3.61,Female,No,Sun,Dinner,4,6.11,29.508,28.20
...,...,...,...,...,...,...,...,...,...,...,...
239,240,29.03,5.92,Male,No,Sat,Dinner,3,8.42,34.836,34.95
240,241,27.18,2.00,Female,Yes,Sat,Dinner,2,4.50,32.616,29.18
241,242,22.67,2.00,Male,Yes,Sat,Dinner,2,4.50,27.204,24.67
242,243,17.82,1.75,Male,No,Sat,Dinner,2,4.25,21.384,19.57
243,244,18.78,3.00,Female,No,Thur,Dinner,2,5.50,22.536,21.78

In [ ]:
mdf.columns

Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'NC1', 'NC2', 'total'],
      dtype='object')

In [ ]:
ndf=mdf.sort_values(by=['tip','total_bill'],ascending=[False,True])
ndf

,ID,total_bill,tip,sex,smoker,day,time,size,NC1,NC2,total
170,171,50.81,10.00,Male,Yes,Sat,Dinner,3,12.50,60.972,60.81
212,213,48.33,9.00,Male,No,Sat,Dinner,4,11.50,57.996,57.33
23,24,39.42,7.58,Male,No,Sat,Dinner,4,10.08,47.304,47.00
59,60,48.27,6.73,Male,No,Sat,Dinner,4,9.23,57.924,55.00
141,142,34.30,6.70,Male,No,Thur,Lunch,6,9.20,41.160,41.00
...,...,...,...,...,...,...,...,...,...,...,...
0,1,16.99,1.01,Female,No,Sun,Dinner,2,3.51,20.388,18.00
67,68,3.07,1.00,Female,Yes,Sat,Dinner,1,3.50,3.684,4.07
92,93,5.75,1.00,Female,Yes,Fri,Dinner,2,3.50,6.900,6.75
111,112,7.25,1.00,Female,No,Sat,Dinner,1,3.50,8.700,8.25
236,237,12.60,1.00,Male,Yes,Sat,Dinner,2,3.50,15.120,13.60

In [ ]:
mdf

,ID,total_bill,tip,sex,smoker,day,time,size,NC1,NC2,total
0,1,16.99,1.01,Female,No,Sun,Dinner,2,3.51,20.388,18.00
1,2,10.34,1.66,Male,No,Sun,Dinner,3,4.16,12.408,12.00
2,3,21.01,3.50,Male,No,Sun,Dinner,3,6.00,25.212,24.51
3,4,23.68,3.31,Male,No,Sun,Dinner,2,5.81,28.416,26.99
4,5,24.59,3.61,Female,No,Sun,Dinner,4,6.11,29.508,28.20
...,...,...,...,...,...,...,...,...,...,...,...
239,240,29.03,5.92,Male,No,Sat,Dinner,3,8.42,34.836,34.95
240,241,27.18,2.00,Female,Yes,Sat,Dinner,2,4.50,32.616,29.18
241,242,22.67,2.00,Male,Yes,Sat,Dinner,2,4.50,27.204,24.67
242,243,17.82,1.75,Male,No,Sat,Dinner,2,4.25,21.384,19.57
243,244,18.78,3.00,Female,No,Thur,Dinner,2,5.50,22.536,21.78