In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L24Pandas"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L24Pandas

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L24Pandas'

In [ ]:
%ls

L24.ipynb  tips.csv

In [ ]:
import pandas as pd

In [ ]:
mdf=pd.read_csv("tips.csv")
mdf

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
mdf.columns

Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
s=mdf["tip"]
s

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [ ]:
# max() min() avg() mean() count() sum()
v=s.max()
print(f"The max tips is: ${v:.2f}")

The max tips is: $10.00

In [ ]:
s=mdf["total_bill"]
v=s.mean()
print(f"The average subtotal is: ${v:.2f}")
# $ 19.79
v=s.sum() # total sales/revenue
print(f"The total revenue is ${v:.2f}")

The average subtotal is: $19.79
The total revenue is $4827.77

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L24Pandas'

In [ ]:
%ls

L24.ipynb  tips.csv

In [ ]:
import pandas as pd
tips_df=pd.read_csv("tips.csv")
tips_df

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
# filtering:
# > >= <= ==
# series -> condition
# and: &
# or: |
# groupby
# 9
c1=tips_df['sex']=='Female'
c2=tips_df['total_bill']>20
c3=tips_df['tip']>5
c=c1&c2&c3
df=tips_df[c]
ndf=df.sort_values(by=["total_bill","tip"],ascending=[False,False])
ndf.to_csv("female_filter_tips.csv",index=False)
ndf
# create a new table (dataframe)

      ID  total_bill   tip     sex smoker   day    time  size
85    86       34.83  5.17  Female     No  Thur   Lunch     4
52    53       34.81  5.20  Female     No   Sun  Dinner     4
155  156       29.85  5.14  Female     No   Sun  Dinner     5
214  215       28.17  6.50  Female    Yes   Sat  Dinner     3

In [ ]:
%ls

female_filter_tips.csv  L24.ipynb  tips.csv

In [ ]:
ndf

      ID  total_bill   tip     sex smoker   day    time  size
85    86       34.83  5.17  Female     No  Thur   Lunch     4
52    53       34.81  5.20  Female     No   Sun  Dinner     4
155  156       29.85  5.14  Female     No   Sun  Dinner     5
214  215       28.17  6.50  Female    Yes   Sat  Dinner     3

In [ ]:
s1=ndf['tip']
n=s1.max()
print(f"The max tip is: ${n:.2f}")

The max tip is: $6.50

In [ ]:
# 10
c1=tips_df['tip']>=6
c2=tips_df['tip']<=8
c=c1&c2
ndf=tips_df[c]
ndf

      ID  total_bill   tip     sex smoker   day    time  size
23    24       39.42  7.58    Male     No   Sat  Dinner     4
47    48       32.40  6.00    Male     No   Sun  Dinner     4
59    60       48.27  6.73    Male     No   Sat  Dinner     4
141  142       34.30  6.70    Male     No  Thur   Lunch     6
183  184       23.17  6.50    Male    Yes   Sun  Dinner     4
214  215       28.17  6.50  Female    Yes   Sat  Dinner     3

In [ ]:
s1=ndf['total_bill']
n=s1.max()
print(f"The max total bill is: ${n:.2f}")

The max total bill is: $48.27

In [ ]:
# 11
s1=tips_df['tip']
s2=tips_df['total_bill']
tips_df["tip_ratio"]=s1/s2
tips_df

      ID  total_bill   tip     sex smoker   day    time  size  tip_ratio
0      1       16.99  1.01  Female     No   Sun  Dinner     2   0.059447
1      2       10.34  1.66    Male     No   Sun  Dinner     3   0.160542
2      3       21.01  3.50    Male     No   Sun  Dinner     3   0.166587
3      4       23.68  3.31    Male     No   Sun  Dinner     2   0.139780
4      5       24.59  3.61  Female     No   Sun  Dinner     4   0.146808
..   ...         ...   ...     ...    ...   ...     ...   ...        ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3   0.203927
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2   0.073584
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2   0.088222
242  243       17.82  1.75    Male     No   Sat  Dinner     2   0.098204
243  244       18.78  3.00  Female     No  Thur  Dinner     2   0.159744

[244 rows x 9 columns]

In [ ]:
# groupby:
# divide the single df into small dfs
s1=tips_df['day']
vs=s1.unique()
print(vs)
s1.value_counts()

['Sun' 'Sat' 'Thur' 'Fri']

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
tips_df

      ID  total_bill   tip     sex smoker   day    time  size  tip_ratio
0      1       16.99  1.01  Female     No   Sun  Dinner     2   0.059447
1      2       10.34  1.66    Male     No   Sun  Dinner     3   0.160542
2      3       21.01  3.50    Male     No   Sun  Dinner     3   0.166587
3      4       23.68  3.31    Male     No   Sun  Dinner     2   0.139780
4      5       24.59  3.61  Female     No   Sun  Dinner     4   0.146808
..   ...         ...   ...     ...    ...   ...     ...   ...        ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3   0.203927
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2   0.073584
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2   0.088222
242  243       17.82  1.75    Male     No   Sat  Dinner     2   0.098204
243  244       18.78  3.00  Female     No  Thur  Dinner     2   0.159744

[244 rows x 9 columns]

In [ ]:
vs

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [ ]:
r=tips_df.groupby(by=['day'])
# r is a collections of small tables
sdf=r.get_group("Fri")
sdf

/tmp/ipykernel_439/3950158994.py:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group("Fri")

      ID  total_bill   tip     sex smoker  day    time  size  tip_ratio
90    91       28.97  3.00    Male    Yes  Fri  Dinner     2   0.103555
91    92       22.49  3.50    Male     No  Fri  Dinner     2   0.155625
92    93        5.75  1.00  Female    Yes  Fri  Dinner     2   0.173913
93    94       16.32  4.30  Female    Yes  Fri  Dinner     2   0.263480
94    95       22.75  3.25  Female     No  Fri  Dinner     2   0.142857
95    96       40.17  4.73    Male    Yes  Fri  Dinner     4   0.117750
96    97       27.28  4.00    Male    Yes  Fri  Dinner     2   0.146628
97    98       12.03  1.50    Male    Yes  Fri  Dinner     2   0.124688
98    99       21.01  3.00    Male    Yes  Fri  Dinner     2   0.142789
99   100       12.46  1.50    Male     No  Fri  Dinner     2   0.120385
100  101       11.35  2.50  Female    Yes  Fri  Dinner     2   0.220264
101  102       15.38  3.00  Female    Yes  Fri  Dinner     2   0.195059
220  221       12.16  2.20    Male    Yes  Fri   Lunch     2   0.180921
221  222       13.42  3.48  Female    Yes  Fri   Lunch     2   0.259314
222  223        8.58  1.92    Male    Yes  Fri   Lunch     1   0.223776
223  224       15.98  3.00  Female     No  Fri   Lunch     3   0.187735
224  225       13.42  1.58    Male    Yes  Fri   Lunch     2   0.117735
225  226       16.27  2.50  Female    Yes  Fri   Lunch     2   0.153657
226  227       10.09  2.00  Female    Yes  Fri   Lunch     2   0.198216