In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L25Pandas"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L25Pandas

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L25Pandas'

In [ ]:
%ls

filtered.csv  L25.ipynb  tips.csv

In [ ]:
import pandas as pd

In [ ]:
mdf=pd.read_csv("tips.csv")
mdf

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
# filtering
# tip bewteen 5 and 9 and total bill is greater than 30
c1=mdf["tip"]>5
c2=mdf["tip"]<9
c3=mdf["total_bill"]>30
c= c1 & c2 & c3
ndf=mdf[c]
ndf.to_csv("filtered.csv",index=False)
ndf

      ID  total_bill   tip     sex smoker   day    time  size
23    24       39.42  7.58    Male     No   Sat  Dinner     4
44    45       30.40  5.60    Male     No   Sun  Dinner     4
47    48       32.40  6.00    Male     No   Sun  Dinner     4
52    53       34.81  5.20  Female     No   Sun  Dinner     4
59    60       48.27  6.73    Male     No   Sat  Dinner     4
85    86       34.83  5.17  Female     No  Thur   Lunch     4
141  142       34.30  6.70    Male     No  Thur   Lunch     6

In [ ]:
%ls

filtered.csv  L25.ipynb  tips.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L25Pandas'

In [ ]:
%ls

filtered.csv  L25.ipynb  tips.csv

In [ ]:
import pandas as pd
tips_df=pd.read_csv("tips.csv")
tips_df

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
# 7
# groupby(): work with/on table/dataframe,
# result in multiple tables/dfs
# divide a single table into small tables
mdf=tips_df
mdf

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
mdf.columns

Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
s1=mdf['tip'] # [] .
s2=mdf['total_bill']
mdf["ratio"]=s1/s2
mdf

      ID  total_bill   tip     sex smoker   day    time  size     ratio
0      1       16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1      2       10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2      3       21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3      4       23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4      5       24.59  3.61  Female     No   Sun  Dinner     4  0.146808
..   ...         ...   ...     ...    ...   ...     ...   ...       ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242  243       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243  244       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 9 columns]

In [ ]:
vs=mdf['day'].unique() # series
print(vs)
n=len(vs)
print(n)

['Sun' 'Sat' 'Thur' 'Fri']
4

In [ ]:
# groupby():
r=mdf.groupby(by=['day'])
n=len(r)

In [ ]:
r.groups.keys()

dict_keys(['Fri', 'Sat', 'Sun', 'Thur'])

In [ ]:
r.get_group("Fri")# dataframe/table

/tmp/ipykernel_432/2558856759.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  r.get_group("Fri")

      ID  total_bill   tip     sex smoker  day    time  size     ratio
90    91       28.97  3.00    Male    Yes  Fri  Dinner     2  0.103555
91    92       22.49  3.50    Male     No  Fri  Dinner     2  0.155625
92    93        5.75  1.00  Female    Yes  Fri  Dinner     2  0.173913
93    94       16.32  4.30  Female    Yes  Fri  Dinner     2  0.263480
94    95       22.75  3.25  Female     No  Fri  Dinner     2  0.142857
95    96       40.17  4.73    Male    Yes  Fri  Dinner     4  0.117750
96    97       27.28  4.00    Male    Yes  Fri  Dinner     2  0.146628
97    98       12.03  1.50    Male    Yes  Fri  Dinner     2  0.124688
98    99       21.01  3.00    Male    Yes  Fri  Dinner     2  0.142789
99   100       12.46  1.50    Male     No  Fri  Dinner     2  0.120385
100  101       11.35  2.50  Female    Yes  Fri  Dinner     2  0.220264
101  102       15.38  3.00  Female    Yes  Fri  Dinner     2  0.195059
220  221       12.16  2.20    Male    Yes  Fri   Lunch     2  0.180921
221  222       13.42  3.48  Female    Yes  Fri   Lunch     2  0.259314
222  223        8.58  1.92    Male    Yes  Fri   Lunch     1  0.223776
223  224       15.98  3.00  Female     No  Fri   Lunch     3  0.187735
224  225       13.42  1.58    Male    Yes  Fri   Lunch     2  0.117735
225  226       16.27  2.50  Female    Yes  Fri   Lunch     2  0.153657
226  227       10.09  2.00  Female    Yes  Fri   Lunch     2  0.198216

In [ ]:
%ls

filtered.csv  L25.ipynb     Sun_tips.csv   tips.csv
Fri_tips.csv  Sat_tips.csv  Thur_tips.csv

In [ ]:
print(vs)
for v in vs: # v: placeholder/container v='Sun' v='Sat'
  # loop body
  print(v)
  print(f"\n\n\nThis data is for day: {v}")
  sdf=r.get_group(v)
  ndf=sdf.sort_values(by=['tip'],ascending=[False])
  ndf.to_csv(f"{v}_tips.csv",index=False)
  n=len(ndf)
  print(n)
  print(f"N orders on {v}: {n}")
  s=ndf['total_bill']
  # unique() max() min() mean() sum() work with series
  n=s.sum() #
  print(f"Sum of total bills for {v}: ${n:.2f}")
  n=s.mean()
  print(f"Average total bill for {v}: ${n:.2f}")
  n=s.max()
  s=ndf['size']
  n=s.sum()
  print(f"For {v}, there are {n} customers.")
  s=ndf['tip']
  n=s.sum()
  print(f"Sum of tips on {v}: ${n:.2f}")
  n=s.mean()
  print(f"Average tip on {v}: ${n:.2f}")

  print(sdf)
  print(ndf)

['Sun' 'Sat' 'Thur' 'Fri']
Sun



This data is for day: Sun
76
N orders on Sun: 76
Sum of total bills for Sun: $1627.16
Average total bill for Sun: $21.41
For Sun, there are 216 customers.
Sum of tips on Sun: $247.39
Average tip on Sun: $3.26
      ID  total_bill   tip     sex smoker  day    time  size     ratio
0      1       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
1      2       10.34  1.66    Male     No  Sun  Dinner     3  0.160542
2      3       21.01  3.50    Male     No  Sun  Dinner     3  0.166587
3      4       23.68  3.31    Male     No  Sun  Dinner     2  0.139780
4      5       24.59  3.61  Female     No  Sun  Dinner     4  0.146808
..   ...         ...   ...     ...    ...  ...     ...   ...       ...
186  187       20.90  3.50  Female    Yes  Sun  Dinner     3  0.167464
187  188       30.46  2.00    Male    Yes  Sun  Dinner     5  0.065660
188  189       18.15  3.50  Female    Yes  Sun  Dinner     3  0.192837
189  190       23.10  4.00    Male    Yes  Sun  Dinner     3  0.173160
190  191       15.69  1.50    Male    Yes  Sun  Dinner     2  0.095602

[76 rows x 9 columns]
      ID  total_bill   tip     sex smoker  day    time  size     ratio
183  184       23.17  6.50    Male    Yes  Sun  Dinner     4  0.280535
47    48       32.40  6.00    Male     No  Sun  Dinner     4  0.185185
181  182       23.33  5.65    Male    Yes  Sun  Dinner     2  0.242177
44    45       30.40  5.60    Male     No  Sun  Dinner     4  0.184211
52    53       34.81  5.20  Female     No  Sun  Dinner     4  0.149382
..   ...         ...   ...     ...    ...  ...     ...   ...       ...
12    13       15.42  1.57    Male     No  Sun  Dinner     2  0.101816
53    54        9.94  1.56    Male     No  Sun  Dinner     2  0.156942
190  191       15.69  1.50    Male    Yes  Sun  Dinner     2  0.095602
43    44        9.68  1.32    Male     No  Sun  Dinner     2  0.136364
0      1       16.99  1.01  Female     No  Sun  Dinner     2  0.059447

[76 rows x 9 columns]
Sat



This data is for day: Sat
87
N orders on Sat: 87
Sum of total bills for Sat: $1778.40
Average total bill for Sat: $20.44
For Sat, there are 219 customers.
Sum of tips on Sat: $260.40
Average tip on Sat: $2.99
      ID  total_bill   tip     sex smoker  day    time  size     ratio
19    20       20.65  3.35    Male     No  Sat  Dinner     3  0.162228
20    21       17.92  4.08    Male     No  Sat  Dinner     2  0.227679
21    22       20.29  2.75  Female     No  Sat  Dinner     2  0.135535
22    23       15.77  2.23  Female     No  Sat  Dinner     2  0.141408
23    24       39.42  7.58    Male     No  Sat  Dinner     4  0.192288
..   ...         ...   ...     ...    ...  ...     ...   ...       ...
238  239       35.83  4.67  Female     No  Sat  Dinner     3  0.130338
239  240       29.03  5.92    Male     No  Sat  Dinner     3  0.203927
240  241       27.18  2.00  Female    Yes  Sat  Dinner     2  0.073584
241  242       22.67  2.00    Male    Yes  Sat  Dinner     2  0.088222
242  243       17.82  1.75    Male     No  Sat  Dinner     2  0.098204

[87 rows x 9 columns]
      ID  total_bill    tip     sex smoker  day    time  size     ratio
170  171       50.81  10.00    Male    Yes  Sat  Dinner     3  0.196812
212  213       48.33   9.00    Male     No  Sat  Dinner     4  0.186220
23    24       39.42   7.58    Male     No  Sat  Dinner     4  0.192288
59    60       48.27   6.73    Male     No  Sat  Dinner     4  0.139424
214  215       28.17   6.50  Female    Yes  Sat  Dinner     3  0.230742
..   ...         ...    ...     ...    ...  ...     ...   ...       ...
237  238       32.83   1.17    Male    Yes  Sat  Dinner     2  0.035638
215  216       12.90   1.10  Female    Yes  Sat  Dinner     2  0.085271
67    68        3.07   1.00  Female    Yes  Sat  Dinner     1  0.325733
111  112        7.25   1.00  Female     No  Sat  Dinner     1  0.137931
236  237       12.60   1.00    Male    Yes  Sat  Dinner     2  0.079365

[87 rows x 9 columns]
Thur



This data is for day: Thur
62
N orders on Thur: 62
Sum of total bills for Thur: $1096.33
Average total bill for Thur: $17.68
For Thur, there are 152 customers.
Sum of tips on Thur: $171.83
Average tip on Thur: $2.77
      ID  total_bill   tip     sex smoker   day    time  size     ratio
77    78       27.20  4.00    Male     No  Thur   Lunch     4  0.147059
78    79       22.76  3.00    Male     No  Thur   Lunch     2  0.131810
79    80       17.29  2.71    Male     No  Thur   Lunch     2  0.156738
80    81       19.44  3.00    Male    Yes  Thur   Lunch     2  0.154321
81    82       16.66  3.40    Male     No  Thur   Lunch     2  0.204082
..   ...         ...   ...     ...    ...   ...     ...   ...       ...
202  203       13.00  2.00  Female    Yes  Thur   Lunch     2  0.153846
203  204       16.40  2.50  Female    Yes  Thur   Lunch     2  0.152439
204  205       20.53  4.00    Male    Yes  Thur   Lunch     4  0.194837
205  206       16.47  3.23  Female    Yes  Thur   Lunch     3  0.196114
243  244       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[62 rows x 9 columns]
      ID  total_bill   tip     sex smoker   day   time  size     ratio
141  142       34.30  6.70    Male     No  Thur  Lunch     6  0.195335
88    89       24.71  5.85    Male     No  Thur  Lunch     2  0.236746
85    86       34.83  5.17  Female     No  Thur  Lunch     4  0.148435
83    84       32.68  5.00    Male    Yes  Thur  Lunch     2  0.152999
142  143       41.19  5.00    Male     No  Thur  Lunch     5  0.121389
..   ...         ...   ...     ...    ...   ...    ...   ...       ...
117  118       10.65  1.50  Female     No  Thur  Lunch     2  0.140845
126  127        8.52  1.48    Male     No  Thur  Lunch     2  0.173709
195  196        7.56  1.44    Male     No  Thur  Lunch     2  0.190476
146  147       18.64  1.36  Female     No  Thur  Lunch     3  0.072961
135  136        8.51  1.25  Female     No  Thur  Lunch     2  0.146886

[62 rows x 9 columns]
Fri



This data is for day: Fri
19
N orders on Fri: 19
Sum of total bills for Fri: $325.88
Average total bill for Fri: $17.15
For Fri, there are 40 customers.
Sum of tips on Fri: $51.96
Average tip on Fri: $2.73
      ID  total_bill   tip     sex smoker  day    time  size     ratio
90    91       28.97  3.00    Male    Yes  Fri  Dinner     2  0.103555
91    92       22.49  3.50    Male     No  Fri  Dinner     2  0.155625
92    93        5.75  1.00  Female    Yes  Fri  Dinner     2  0.173913
93    94       16.32  4.30  Female    Yes  Fri  Dinner     2  0.263480
94    95       22.75  3.25  Female     No  Fri  Dinner     2  0.142857
95    96       40.17  4.73    Male    Yes  Fri  Dinner     4  0.117750
96    97       27.28  4.00    Male    Yes  Fri  Dinner     2  0.146628
97    98       12.03  1.50    Male    Yes  Fri  Dinner     2  0.124688
98    99       21.01  3.00    Male    Yes  Fri  Dinner     2  0.142789
99   100       12.46  1.50    Male     No  Fri  Dinner     2  0.120385
100  101       11.35  2.50  Female    Yes  Fri  Dinner     2  0.220264
101  102       15.38  3.00  Female    Yes  Fri  Dinner     2  0.195059
220  221       12.16  2.20    Male    Yes  Fri   Lunch     2  0.180921
221  222       13.42  3.48  Female    Yes  Fri   Lunch     2  0.259314
222  223        8.58  1.92    Male    Yes  Fri   Lunch     1  0.223776
223  224       15.98  3.00  Female     No  Fri   Lunch     3  0.187735
224  225       13.42  1.58    Male    Yes  Fri   Lunch     2  0.117735
225  226       16.27  2.50  Female    Yes  Fri   Lunch     2  0.153657
226  227       10.09  2.00  Female    Yes  Fri   Lunch     2  0.198216
      ID  total_bill   tip     sex smoker  day    time  size     ratio
95    96       40.17  4.73    Male    Yes  Fri  Dinner     4  0.117750
93    94       16.32  4.30  Female    Yes  Fri  Dinner     2  0.263480
96    97       27.28  4.00    Male    Yes  Fri  Dinner     2  0.146628
91    92       22.49  3.50    Male     No  Fri  Dinner     2  0.155625
221  222       13.42  3.48  Female    Yes  Fri   Lunch     2  0.259314
94    95       22.75  3.25  Female     No  Fri  Dinner     2  0.142857
90    91       28.97  3.00    Male    Yes  Fri  Dinner     2  0.103555
101  102       15.38  3.00  Female    Yes  Fri  Dinner     2  0.195059
98    99       21.01  3.00    Male    Yes  Fri  Dinner     2  0.142789
223  224       15.98  3.00  Female     No  Fri   Lunch     3  0.187735
100  101       11.35  2.50  Female    Yes  Fri  Dinner     2  0.220264
225  226       16.27  2.50  Female    Yes  Fri   Lunch     2  0.153657
220  221       12.16  2.20    Male    Yes  Fri   Lunch     2  0.180921
226  227       10.09  2.00  Female    Yes  Fri   Lunch     2  0.198216
222  223        8.58  1.92    Male    Yes  Fri   Lunch     1  0.223776
224  225       13.42  1.58    Male    Yes  Fri   Lunch     2  0.117735
99   100       12.46  1.50    Male     No  Fri  Dinner     2  0.120385
97    98       12.03  1.50    Male    Yes  Fri  Dinner     2  0.124688
92    93        5.75  1.00  Female    Yes  Fri  Dinner     2  0.173913

/tmp/ipykernel_432/3180394171.py:6: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(v)
/tmp/ipykernel_432/3180394171.py:6: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(v)
/tmp/ipykernel_432/3180394171.py:6: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(v)
/tmp/ipykernel_432/3180394171.py:6: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(v)